# Code Smell Detector Configuration
# This file controls which smells are detected and their thresholds

# Language setting (currently only Python is supported)
language: "python"

# Which smells are enabled by default (can be overridden by CLI)
smells:
  LongMethod: true
  GodClass: true
  DuplicatedCode: true
  LargeParameterList: true
  MagicNumbers: true
  FeatureEnvy: true

# Long Method Detection Settings
long_method:
  # Source Lines of Code threshold
  sloc: 20
  # Cyclomatic complexity threshold
  cyclomatic: 12

# God Class (Blob) Detection Settings
god_class:
  # ATFD (Access to Foreign Data) threshold
  atfd_few: 2
  # WMC (Weighted Method Count) threshold
  wmc_very_high: 10
  # TCC (Tight Class Cohesion) threshold
  tcc_one_third: 0.6

# Large Parameter List Detection Settings
large_parameter_list:
  # Maximum number of parameters (excluding self)
  params: 5

# Duplicated Code Detection Settings
duplicated_code:
  min_block_lines: 3

# Magic Numbers Detection Settings
magic_numbers:
  # Minimum occurrences to be considered magic
  min_occurrences: 3
  # Numbers to ignore (common values)
  whitelist: [0, 1, -1]

# Feature Envy Detection Settings
feature_envy:
  min_sloc: 10
  atfd_threshold: 5
  laa_threshold: 0.33
  fdp_threshold: 2

# Report Generation Settings
report:
  # Output format: json | table
  format: "json"
  # Include detailed metrics in report
  include_metrics: true
  # Show which smells were actively checked
  show_active_smells: true
