# Lenient Configuration - Higher thresholds for legacy code
language: "python"

smells:
  LongMethod: true
  GodClass: true
  DuplicatedCode: true
  LargeParameterList: true
  MagicNumbers: false    # Disabled for legacy code
  FeatureEnvy: true

long_method:
  sloc: 50          # Lenient: 50 lines instead of 30
  cyclomatic: 20    # Lenient: 20 complexity instead of 12

god_class:
  max_methods: 30   # Lenient: 30 methods instead of 20
  max_fields: 25    # Lenient: 25 fields instead of 15
  max_coupling: 25  # Lenient: 25 coupling instead of 15

large_parameter_list:
  params: 8         # Lenient: 8 params instead of 6

duplicated_code:
  shingle_size: 40
  similarity: 0.95  # Lenient: 95% similarity instead of 90%
  min_chunk_tokens: 100

magic_numbers:
  min_occurrences: 5  # Lenient: 5 occurrences instead of 3
  whitelist: [0, 1, -1, 2, 3, 4, 5, 10, 100, 1000]

feature_envy:
  min_sloc: 15
  foreign_access_ratio: 2.0  # Lenient: 2.0 ratio instead of 1.5
  min_foreign_accesses: 5    # Lenient: 5 accesses instead of 3

report:
  format: "json"
  include_metrics: true
  show_active_smells: true
